import type { Metadata } from 'next'
import './globals.css'
import { Poppins } from 'next/font/google'
import { Providers } from '@/store/providers'

const poppins = Poppins({
    weight: ['300', '400', '500', '600', '700', '800'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-poppins',
})

export const metadata: Metadata = {
    title: 'Fast Delivery',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={`${poppins.variable}`}>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
