name: Build, Test, and Deploy

on:
  push:
    branches: "develop"
  pull_request:
    branches: "develop"

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy with Docker
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      
name: Checkout code
      uses: actions/checkout@v3

      
name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

      
name: Install Dependencies
      run: npm ci

      
name: Run ESLint
      run: npm run lint

      
name: Run Tests
      run: npm run test

      
name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

      
name: Build Docker Image
      run: |
        docker build -t chacurbanos-front.

      
name: Run Docker Container for Testing
      run: |
        docker run -d -p 3000:3000 --name chacurbanos-front-container